class Courses {
  // Listas de Cursos
  static const List<String> cursos = [
    'First',
    'One',
    'Tech',
  ];

  // Projetos dos cursos:

  // First
  static const List<String> cursosFirst = [
    'Balança',
    'Castelo',
    'Minerador',
    'Cachorrinho',
    'Cobra',
    'Mamute',
    'Equilíbrio',
    'Robô Baterista',
    'Dom Quixote',
    'Lançador de Origami',
    'Cinema',
    'Helicóptero',
    'Basquete',
    'Macaco',
    'Libélula',
    'Barquinho',
    'Penbolin',
    'Cofre',
    'Arco e Flecha',
    'Humanóide',
    'Boitátá',
    'Microondas',
    'Robô Aspirador',
    'Pinguim',
    'Ventilador',
    'Praça Iluminada',
    'Estações do Tempo',
    'Corrida das Cores',
    'Automóvel',
    'Parquinho',
    'Controle de Qualidade',
    'Drone',
    'Farol da Barra',
    'Geladeira',
    'Guindaste',
    'Hidrelétrica',
    'Chute ao gol',
    'Mixer',
    'Ônibus',
    'Navio Cargueiro',
    "Moinho D'água",
    'Helicóptero de Guerra',
    'Trator',
    'Submarino',
    'Seguidor de Linha'
  ];

  // One
  static const List<String> cursosOne = [
    'Dinossauro',
    'Submarino',
    'Lançador de foguete',
    'Cérebro',
    'Pato Robô',
    'Escavadeira',
    'Hidrelétrica',
    'Astrolábio',
    'Lagarto',
    'Automóvel',
    'Castor',
    'Pedágio',
    'Desvio de obstáculos',
    'Teleférico',
    'Wall-E',
    'Robô Ginasta',
    'Vara de Pesca',
    'Halloween',
    'Chapéu Mexicano',
    'Máquina de Flores',
    'Helicóptero',
    'Robô Golfista',
    'Caminhão de Bombeiro',
    'Game GrandPix',
    'Trator',
    'DrawingBot',
    'Trem Segue Linha',
    'Caminhão de Lixo',
    'Casa Automática',
    'Labirinto',
    'CleanBot',
    'Caixa com Senha',
    'Caixa de Música',
    'Tirolesa',
    'Casa Fotovoltáica',
    'Elevador',
    'Energia Eólica',
    'Catapulta',
    'Carro com chave',
    'Separador Black and White',
    'Dinossauro T-rex',
    'Carro antiqueda',
    'Carro de Demolição',
    'Moto',
    'Ambulância'
  ];

  // Tech
  static const List<String> cursosTech = [];
}
